Basketball/Basketball.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Basketball.Data.Repositories;
using Basketball.Scrape.Service;

namespace Basketball.Web.Controllers.MVC
{
    public class PlayerController : Controller
    {
        private readonly ICountryRepository _countryRepository;

        public PlayerController(ICountryRepository countryRepository)
        {
            this._countryRepository = countryRepository;
        }
        // GET: Player
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetPlayerInfo(string url)
        {
            PlayerInfo info = new PlayerInfo();
            var urlList = info.GetPlayerUrls(url, "China");
            return View(@"\Views\Player\Index.cshtml");
        }

        [HttpGet]
        public ActionResult Add()
        {
            var countries = _countryRepository.GetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Add(string firstName)
        {
            return View();
        }
    }
}

Basketball/Basketball.Web/Views/Player/Add.cshtml
@model IEnumerable<Basketball.Models.Models.Country>
@{
    ViewBag.Title = "Add";
}
@Html.Partial("_AdminSubnav")
<h2>Add new player</h2>

@using (Html.BeginForm("Add", "Player", FormMethod.Post))
{
    <table width="50%">
        <tr><td width="30%"><label>First Name</label> </td><td><input type="text" name="firstName" /></td></tr>
        <tr><td><label>Last Name</label> </td><td><input type="text" name="lastName" /></td></tr>
        <tr><td><label>Height</label> </td><td><input type="text" name="height" /></td></tr>
        <tr><td><label>Position</label> </td><td><input type="text" name="position" /></td></tr>
        <tr><td><label>Nationality</label> </td><td><input type="text" name="nationality" /></td></tr>
        <tr><td><label>Naturalized nationality</label> </td><td><input type="text" name="naturalizedNationality" /></td></tr>
    </table>

    <input type="submit" value="Submit" />
}

Basketball/Basketball.Web/Views/Player/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<form action="/Player/GetPlayerList" method="post">
        <input type="text" name="url" />
        <input type="submit" value="Submit" />
    </form>*@

@using (Html.BeginForm("GetPlayerInfo", "Player", FormMethod.Post))
{
    <input type="text" name="url" />
    <input type="submit" value="Submit" />
}